### ISSUE TITLE
Where did face-dectector/res10_300x300_ssd_iter_140000.caffemodel come from?

### ISSUE THREAD

**Issue by alpiepho** [carolinedunn/Face_Mask_Detection#2]
Thank you for the demo.  It was fun to setup.
As I was studying the files, I found the pre-trained model for face detection, but could not figure out where it came from.  Looking for that file on the net, I found several places where it and the associated deploy.prototxt were added to various github projects and even a reference to OpenCV.  But I could not find the source anywhere.
If you have some time, I would love to learn where this came from and how you learned about this model.
Thanks, Al

**Comment by carolinedunn** [comment]
I believe Caffe came from Berkeley AI Research. Check this out: https://caffe.berkeleyvision.org/
