### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by rogdevil** [carolinedunn/Face_Mask_Detection#3]
when i run the command for webcam it shows me the error
![image](https://user-images.githubusercontent.com/43280610/105436487-4b613680-5c85-11eb-8e01-4699b72f9c19.png)

**Comment by ikrambenabdelouahab** [comment]
This error is due to the version of h5py library. **`#pip3 install h5py==2.10.0`** should solve the problem.

**Comment by rogdevil** [comment]
@ikrambenabdelouahab  thank you. this solved the problem :)
